# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Scan for changes to the nodes integrity
# *********************************************************************
---
- hosts: all
  tasks:
    - debug:
        msg: "Scan the node for changes to it's integrity" 

    - shell: /opt/ds_agent/dsa_control --scanForChanges
      when: ansible_os_family != "Windows"
      become: true

    - win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' --scanForChanges"
      when: ansible_os_family == "Windows"