# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Ask the Deep Security agent to create a diagnostic package
# *********************************************************************
---
- hosts: all
  tasks:
    - debug:
        msg: "Ask the Deep Security agent to create a diagnostics package" 

    - shell: /opt/ds_agent/dsa_control -d
      when: ansible_os_family != "Windows"
      become: true

    - win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' -d"
      when: ansible_os_family == "Windows"