# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Ask the Deep Security agent to check-in
# *********************************************************************
---
- hosts: all
  tasks:
    - debug:
        msg: "Ask the Deep Security agent to check in with the Deep Security manager" 

    - shell: /opt/ds_agent/dsa_control -m
      when: ansible_os_family != "Windows"
      become: true

    - win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' -m"
      when: ansible_os_family == "Windows"