---
- hosts: all
  vars_files:
    - vars/dsa-deploy.yml
  tasks:
    - name: Reset the Deep Security agent
      command: /opt/ds_agent/dsa_control -r

    - name: Make sure the agent has gathered the required metadata
      pause: seconds=3

    - name: Activate the Deep Security agent
      command: /opt/ds_agent/dsa_control -a dsm://{{ dsa_activation_hostname }}:{{ dsa_activation_port }}/ "tenantID:{{ tenant_id }}" "tenantPassword:{{ tenant_password }}"