# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Recommend a security policy for the node
# *********************************************************************
---
- hosts: all
  tasks:
    - debug:
        msg: "Create a recommended securty policy for the node" 

    - shell: /opt/ds_agent/dsa_control -m "RecommendationScan:true"
      when: ansible_os_family != "Windows"
      become: true

    - win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' -m 'RecommendationScan:true'"
      when: ansible_os_family == "Windows"