# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Create an integrity baseline for the current node
# *********************************************************************
---
- hosts: all
  tasks:
    - debug:
        msg: "Ask the Deep Security agent to create an integrity baseline" 

    - shell: /opt/ds_agent/dsa_control --buildBaseline
      when: ansible_os_family != "Windows"
      become: true

    - win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' --buildBaseline"
      when: ansible_os_family == "Windows"