---
language: python
python: "2.7"

sudo: required

services:
#  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Install ansible dependencies
  - ansible-playbook tests/setup.yml -i tests/travis.hosts --connection=local

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nhost_key_checking = False' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/travis.hosts --syntax-check --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/