# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Install, Activate and Manage Trend Micro Deep Security Agent
# *********************************************************************
---
- name: "Listing parameters"
  debug:
    msg:
       - "action                       : {{ action }}"
       - "dsm_agent_download_hostname  : {{ dsm_agent_download_hostname }}"
       - "dsm_agent_download_port      : {{ dsm_agent_download_port }}"
       - "dsm_agent_activation_hostname: {{ dsm_agent_activation_hostname }}"
       - "dsm_agent_activation_port    : {{ dsm_agent_activation_port }}"
       - "policy_id                    : {{ policy_id }}"
       - "force_reactivation           : {{ force_reactivation }}"

- name: Deploy (Install then Activate) Trend Micro Deep Security Agent
  include_tasks: deploy.yml
  when: action == 'deploy'

- name: Install Trend Micro Deep Security Agent
  include_tasks: install.yml
  when: action == 'install'

- name: Activate Trend Micro Deep Security Agent
  include_tasks: activate.yml
  when: action == 'activate'

- name: Manage Trend Micro Deep Security Agent
  include_tasks: manage.yml
  when: action != 'deploy' and action != 'install' and action != 'activate'