# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Install, Activate and Manage Trend Micro Deep Security Agent
# *********************************************************************
---
- name: "Announce deprecated for variable 'action'"
  debug:
    msg: "[Warning] the variable 'action' is deprecated, please change to use 'operation' instead"
  when: action is defined and (operation is not defined)

- name: "Convert action to operation"
  set_fact:
    operation: "{{ action }}"
  when: action is defined and (operation is not defined)

- name: "Listing parameters"
  debug:
    msg:
       - "operation                    : {{ operation }}"
       - "dsm_agent_download_hostname  : {{ dsm_agent_download_hostname }}"
       - "dsm_agent_download_port      : {{ dsm_agent_download_port }}"
       - "dsm_agent_activation_hostname: {{ dsm_agent_activation_hostname }}"
       - "dsm_agent_activation_port    : {{ dsm_agent_activation_port }}"
       - "policy_id                    : {{ policy_id }}"
       - "group_id                     : {{ group_id }}"
       - "force_reactivation           : {{ force_reactivation }}"

- name: Deploy (Install then Activate) Trend Micro Deep Security Agent
  include_tasks: deploy.yml
  when: operation == 'deploy'

- name: Install Trend Micro Deep Security Agent
  include_tasks: install.yml
  when: operation == 'install'

- name: Activate Trend Micro Deep Security Agent
  include_tasks: activate.yml
  when: operation == 'activate'

- name: Manage Trend Micro Deep Security Agent
  include_tasks: manage.yml
  when: operation != 'deploy' and operation != 'install' and operation != 'activate'
