# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Activate the Deep Security Agent (For both Windows and Linux)
# *********************************************************************
---
- include_tasks: activate-win.yml
  when: ansible_os_family == "Windows"

- include_tasks: activate-linux.yml
  when: ansible_os_family != "Windows"