# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Recommend a security policy for the node
# *********************************************************************
---
# *********************************************************************
# * Check if DSA installed properly
# *********************************************************************
- debug:
    msg: "Check if DSA installed properly."

- stat:
    path: /opt/ds_agent/dsa_control
  register: dsaControl

- fail:
    msg: 
        - "Could not find command /opt/ds_agent/dsa_control to operate DSA."
        - "Please make sure Deep Security Agent has been installed"
  when: dsaControl.stat.size is not defined 

# *********************************************************************
# * Create a recommended securty policy for the node
# *********************************************************************
- debug:
    msg: "Create a recommended securty policy for the node" 

- shell: /opt/ds_agent/dsa_control -m "RecommendationScan:true"
  when: ansible_os_family != "Windows"
  become: true

- win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' -m 'RecommendationScan:true'"
  when: ansible_os_family == "Windows"