# Copyright 2018, Trend Micro
#
# License as per [repo](master/LICENSE)
#
# *********************************************************************
# * Scan for changes to the nodes integrity
# *********************************************************************
---
# *********************************************************************
# * Check if DSA installed properly
# *********************************************************************
- debug:
    msg: "Check if DSA installed properly."

- stat:
    path: /opt/ds_agent/dsa_control
  register: dsaControl

- fail:
    msg: 
        - "Could not find command /opt/ds_agent/dsa_control to operate DSA."
        - "Please make sure Deep Security Agent has been installed"
  when: dsaControl.stat.size is not defined 

# *********************************************************************
# * Scan the node for changes to it's integrity
# *********************************************************************
- debug:
    msg: "Scan the node for changes to it's integrity" 

- shell: /opt/ds_agent/dsa_control --scanForChanges
  when: ansible_os_family != "Windows"
  become: true

- win_shell: "& 'C:\\Program Files\\Trend Micro\\Deep Security Agent\\dsa_control' --scanForChanges"
  when: ansible_os_family == "Windows"